name: Generate ASCII Artwork

on: 
  push

jobs:
  build-job-1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f dragon "Run for cover, I am Dragon....RAW" >> dragon.txt
        
    - name: upload dragon text file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text file 
        path: dragon.txt
  
  test-job-2:
    needs: build-job-1
    runs-on: ubuntu-latest

    steps:
    - name: download dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text file

    - name: Test file exists
      run: grep -i "dragon" dragon.txt
  
  deploy-job-3:
    needs: test-job-2
    runs-on: ubuntu-latest

    steps:
    - name: download dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text file

    - name: Read file
      run: cat dragon.txt